### ISSUE TITLE
Bug with JSON file containing a string value containing `//`

### ISSUE THREAD

**Issue by k8-zali** [Razza2018/real-time-twig#8]
To replicate:
- Add the following JSON file:
```
{
  "test": "hello//world"
}
```
- An error message will appear.

Possible solution:
- Change all double forward slashes to be escaped. `//` to `\/\/`.

**Comment by Razza2018** [comment]
I figured out why this bug has appeared all of a sudden. The update to allow comments has broken double slashes.
A double slash is being treated as a comment which is commenting out the rest of the line, hence why we're getting issues as the string is never closed in the JSON.

**Comment by Razza2018** [comment]
This has been fixed.
